apiVersion: apps/v1
kind: Deployment
metadata:
  name: yei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yei
  template:
    metadata:
      labels:
        app: yei
    spec:
      containers:
      - image: okteto.dev/mei:latest
        name: yei
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "0bd76543-c6c6-4500-b4c0-37e9cc88dadd"
        - name: Vless_Path
          value: "/mei123"
        - name: Vmess_UUID
          value: "0bd76543-c6c6-4500-b4c0-37e9cc88dadd"
        - name: Vmess_Path
          value: "/mei124"
        - name: Share_Path
          value: "/Share123"
